# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'benutzer.ui'
#
# Created: Mon Oct 28 19:56:48 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(801, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.newPlayerName = QtGui.QLineEdit(self.widget)
        self.newPlayerName.setText(_fromUtf8(""))
        self.newPlayerName.setObjectName(_fromUtf8("newPlayerName"))
        self.horizontalLayout.addWidget(self.newPlayerName)
        self.addPlayer = QtGui.QPushButton(self.widget)
        self.addPlayer.setObjectName(_fromUtf8("addPlayer"))
        self.horizontalLayout.addWidget(self.addPlayer)
        self.countplayers = QtGui.QSpinBox(self.widget)
        self.countplayers.setMinimum(2)
        self.countplayers.setMaximum(6)
        self.countplayers.setProperty("value", 4)
        self.countplayers.setObjectName(_fromUtf8("countplayers"))
        self.horizontalLayout.addWidget(self.countplayers)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.counttables = QtGui.QSpinBox(self.widget)
        self.counttables.setMinimum(1)
        self.counttables.setProperty("value", 7)
        self.counttables.setObjectName(_fromUtf8("counttables"))
        self.horizontalLayout.addWidget(self.counttables)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtGui.QWidget(self.centralwidget)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.spieler = QtGui.QTableWidget(self.widget_2)
        self.spieler.setMaximumSize(QtCore.QSize(30000, 16777215))
        self.spieler.setFocusPolicy(QtCore.Qt.NoFocus)
        self.spieler.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.spieler.setAcceptDrops(False)
        self.spieler.setDragEnabled(True)
        self.spieler.setDragDropOverwriteMode(False)
        self.spieler.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.spieler.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.spieler.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.spieler.setObjectName(_fromUtf8("spieler"))
        self.spieler.setColumnCount(3)
        self.spieler.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.spieler.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.spieler.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.spieler.setHorizontalHeaderItem(2, item)
        self.spieler.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_2.addWidget(self.spieler)
        self.widget_3 = QtGui.QWidget(self.widget_2)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.widget_4 = QtGui.QWidget(self.widget_3)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.widget_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.games = QtGui.QLabel(self.widget_4)
        self.games.setText(_fromUtf8(""))
        self.games.setObjectName(_fromUtf8("games"))
        self.horizontalLayout_3.addWidget(self.games)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.playedwith = QtGui.QTableWidget(self.widget_3)
        self.playedwith.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.playedwith.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.playedwith.setObjectName(_fromUtf8("playedwith"))
        self.playedwith.setColumnCount(3)
        self.playedwith.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.playedwith.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.playedwith.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.playedwith.setHorizontalHeaderItem(2, item)
        self.playedwith.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.playedwith)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.verticalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.addPlayer, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.addplayer)
        QtCore.QObject.connect(self.newPlayerName, QtCore.SIGNAL(_fromUtf8("returnPressed()")), MainWindow.addplayer)
        QtCore.QObject.connect(self.spieler, QtCore.SIGNAL(_fromUtf8("cellChanged(int,int)")), MainWindow.cell_changed)
        QtCore.QObject.connect(self.spieler, QtCore.SIGNAL(_fromUtf8("doubleClicked(QModelIndex)")), MainWindow.deleteplayer)
        QtCore.QObject.connect(self.spieler, QtCore.SIGNAL(_fromUtf8("currentCellChanged(int,int,int,int)")), MainWindow.update_playedwith)
        QtCore.QObject.connect(self.countplayers, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), MainWindow.players_per_table_changed)
        QtCore.QObject.connect(self.counttables, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), MainWindow.tables_changed)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.newPlayerName, self.addPlayer)
        MainWindow.setTabOrder(self.addPlayer, self.spieler)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Durak-Spieler", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Neuer Spieler Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.addPlayer.setText(QtGui.QApplication.translate("MainWindow", "Hinzufügen", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Spieler pro", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Tische", None, QtGui.QApplication.UnicodeUTF8))
        self.spieler.setSortingEnabled(False)
        item = self.spieler.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Num", None, QtGui.QApplication.UnicodeUTF8))
        item = self.spieler.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Punkte", None, QtGui.QApplication.UnicodeUTF8))
        item = self.spieler.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Anzahl Spiele:", None, QtGui.QApplication.UnicodeUTF8))
        self.playedwith.setSortingEnabled(True)
        item = self.playedwith.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        item = self.playedwith.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Num", None, QtGui.QApplication.UnicodeUTF8))
        item = self.playedwith.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Anzahl", None, QtGui.QApplication.UnicodeUTF8))

